#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_rethinkdb="$(rethinkdb --version 2>&- | awk 'NR == 1 { print $2 }' || true)"
  jq -n --arg rethinkdb "$ver_rethinkdb" '{rethinkdb: $rethinkdb}'
}

version "$@"
